settings:
  title: 'CS STATUS'
  url: 'https://cf-workers-status-page-production.cs-shop.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Tutti i servizi ONLINE'
  notAllmonitorsOperational: 'Alcuni servizi OFFLINE'
  monitorLabelOperational: 'ONLINE'
  monitorLabelNotOperational: 'OFFLINE'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: cs-shop # unique identifier
    name: cs-shop.it
    description: 'Sito CS SHOP' # default=empty
    url: 'https://cs-shop.it/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: ServerFivem
    name: CS SHOP FiveM
    description: 'Server FiveM CS SHOP'
    url: 'https://fivem.cs-shop.it'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
